version: '3.7'
services:
  trackfic-backend.trackficdata.online:
    container_name: trackfic-backend.trackficdata.online
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    build:
      context: ./

  caddy:
    image: caddy/caddy:2.2.1-alpine
    container_name: caddy
    restart: unless-stopped
    ports: 2020:2020
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
