export default {
  privateKeyEncoded: "ACCESS_TOKEN_PRIVATE_KEY",
  publicKeyEncoded: "ACCESS_TOKEN_PUBLIC_KEY",
  dbUri: "DB_CONNECTION",
  port: "PORT",
  domain: 'DOMAIN',
  googleAPIKey: 'GOOGLE_API_KEY',
  saltWorkFactor: 'SALT_WORK_FACTOR',
  accessTokenTtl: 'ACCESS_TOKEN_TTL',
  refreshTokenTtl: 'REFRESH_TOKEN_TTL',
  accessTokenTtlMs: 'ACCESS_TOKEN_TTL_MS',
  refreshTokenTtlMs: 'REFRESH_TOKEN_TTL_MS',
  timezone: 'TIMEZONE',
  mapsAPI: 'MAPS_API',
  nodeConfigDir: 'NODE_CONFIG_DIR',
}