import dotenv from 'dotenv'
dotenv.config()

process.env.NODE_CONFIG_DIR = './config'

import config from 'config'
import connect from './utils/connect'
import log from './utils/logger'
import createServer from './utils/server'

const port = config.get<number>('port')
const app = createServer()
log.info(`this is process.env ${JSON.stringify(process.env)}`)
log.info('Starting server')

app.listen(port, async () => {
  log.info(`app is running at ${port}`)
  await connect()
})

let x = {
  NODE_VERSION: '14.21.1',
  HOSTNAME: 'd592c5db606f',
  YARN_VERSION: '1.22.19',
  HOME: '/root',
  PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
  PWD: '/src',
  NODE_ENV: 'production',
  ACCESS_TOKEN_PUBLIC_KEY:
    'LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlHZk1BMEdDU3FHU0liM0RRRUJBUVVBQTRHTkFEQ0JpUUtCZ1FDWHpaZXJweDlxZGFlbHd0MVU3TkNwV1hRSwprbTFPVzRvaERGLzdnMDF4RHRZZjhOb3g5d3poaFZRckZEK0c0ZWFKb1d4SWhKWVFUZ1Q0aWpNbHBqWHMwN01jCndrdGNNWDQ5aDZFb282WmRkT01sMzgwVXBpdmthTytoODBtaUc0SkNGQU0wRzBwVW9lTlQ4aDZMOXpIcXIveUUKb0JSZDNSQXNxeGVDS3dLcnN3SURBUUFCCi0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQ',
  ACCESS_TOKEN_PRIVATE_KEY:
    'LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlDWEFJQkFBS0JnUUNYelplcnB4OXFkYWVsd3QxVTdOQ3BXWFFLa20xT1c0b2hERi83ZzAxeER0WWY4Tm94Cjl3emhoVlFyRkQrRzRlYUpvV3hJaEpZUVRnVDRpak1scGpYczA3TWN3a3RjTVg0OWg2RW9vNlpkZE9NbDM4MFUKcGl2a2FPK2g4MG1pRzRKQ0ZBTTBHMHBVb2VOVDhoNkw5ekhxci95RW9CUmQzUkFzcXhlQ0t3S3Jzd0lEQVFBQgpBb0dBU2RZcGNNZXdRek1KSVZwZ0Y3KzhXckwwKzNOdmtVNTdLRW9Cb2ErakNsdmlFTlV3L0Y2ak9FcUd2eEZ4Ck9PVkdJaW1QSnRLK3Z4MkQwM1E5SHBIeTVnZkczUTBoWHE4UkFCZnpPa2dLT1FKWUViL0N0a2FkUm85c3FQcHcKUHRYYUZyd1lOUGV2cXpVeWRrNVk0aW1RTjB5eWNtS1BpcmdXUDJHR1pqOG5BeEVDUVFETW1XSTZCa0UrOHAwSApQc3pya3BEbEFvM3AvNG9NVzRYZ294QmJJdUhNdXpZWmk2ZDZGVXZjT2pHSTg4a3RUQlNNSWh3akY1Sy9sSUJVClJYY0tqektKQWtFQXZmQ3RITjZvTHMyMk1YcDFBWkJUU0lmTHAvOEM0bkxmVzZWTWJvUitTdzlSNU1hdFR1VEkKVzRzZWVCeG4xL0RVODhJaFU1NzltYVlNWDhURk1JVE5Xd0pBVEFQTXo5d1ZENnNhRm1BSnlKaEt4eHNjMk14OQpZTHY4VUlxbEFBZEV0MGp5LzZpNFQ0NXNBZVdKRStYblg3SDlqRmI3OXpuQjV2WG9lK2JYSkpBeGFRSkJBSzlQCldlaWdsZWlGRkJsODVrdm9Nd1pwMkE0WjhFYWtNZ1g3ZnAwdkN3WXFnTExBc2F0MHZIekozZmlNZDBnM1Q4WWcKc3ZQa2RqdC9xRUlvY3J5Q2hxc0NRR25JbkZEazlmQzVDOEcxRXoyTi9wMFd6dG9QRE5LZllWREdaOElSTWpFeQpyUGVIMDNDSWhJb2g2UVBQZzAyR0tDM1Z1bVF4Z3dPZTJ3a1EyT2dIWUxFPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQ',
  DOMAIN: 'vercel',
  GOOGLE_API_KEY: 'AIzaSyDsVyKhSI8vWMOOS74QHQe2rD0JKfJ3t2U',
  SALT_FACTOR: '10',
  ACCESS_TOKEN_TTL: '1d',
  REFRESH_TOKEN_TTL: '1y',
  ACCESS_TOKEN_TTL_MS: '60 * 60 * 1000 * 24',
  REFRESH_TOKEN_TTL_MS: '365 * 24 * 60 * 60 * 1000',
  TIMEZONE: 'America/New_York',
  MAPS_API: 'AIzaSyDQaQ22jPs4WUnCh7Fp9kMdYOl1METK2GU',
  NODE_CONFIG_DIR: './config',
}
